# Generated by Django 6.0.2 on 2026-03-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('paginas', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=20)),
                ('idioma', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('cadastrado_por', models.CharField(max_length=100)),
            ],
        ),
    ]
